branch-defaults:
  default:
    environment: shippable
    group_suffix: null
global:
  application_name: image-of-the-day
  default_ec2_keyname: shippable
  default_platform: Python
  default_region: us-east-1
  profile: eb-cli
  sc: git